# Generate manuscript tables directly from the audited probability reporting CSVs.
args<-commandArgs(trailingOnly=TRUE)
root<-if(length(args)) args[1] else getwd()
paper<-file.path(root,"analysis")
report<-file.path(root,"artifacts/feedback2_revision/reporting")
m<-read.csv(file.path(report,"probability_model_means.csv"))
t<-read.csv(file.path(report,"probability_paired_inference.csv"))
scopes<-c("Kather_selected_faithfulness_primary_jointly_correct_true_class",
          "Kather_random_prediction_independent_primary_jointly_correct_true_class",
          "CRC_crc_common_seven_external_primary_jointly_correct_true_class",
          "CRC_crc_common_seven_external_all_image_true_class_sensitivity")
labels<-c("Kather selected","Kather random","CRC conditional","CRC class-complete")
auc<-"top_minus_random_probability_reduction_auc"
pformat<-function(p) if(p<.0001) "$<0.0001$" else sprintf("%.4f",p)
table_file<-function(file,caption,label,columns,header,rows) {
    writeLines(c("% Generated by Methods/Feedback2/build_probability_tables.R",
        "\\begin{table}[htbp]\\centering\\small",paste0("\\caption{",caption,"}\\label{",label,"}"),
        paste0("\\begin{tabular}{",columns,"}\\toprule"),paste0(header," \\\\"),"\\midrule",
        paste0(rows," \\\\"),"\\bottomrule\\end{tabular}","\\end{table}"),file.path(paper,file))
}
rows<-vapply(seq_along(scopes),function(i) {
    d<-m[m$scope==scopes[i],];d<-d[match(c("ResNet18","DINOv2","UNI"),d$model),]
    p<-t[t$scope==scopes[i]&t$metric==auc&t$model_a=="UNI"&t$model_b=="DINOv2",]
    stopifnot(nrow(d)==3,nrow(p)==1,length(unique(d$images))==1)
    paste(c(labels[i],d$images[1],sprintf("%.4f",d[[auc]]),pformat(p$p_holm)),collapse=" & ")
},"")
table_file("feedback2_probability_means.tex",
    "Probability-deletion sensitivity with deterministic ties. Values are image-weighted mean top-minus-random probability-drop AUCs over deletion fractions 0--0.5; positive values favor top deletion. The final column gives the UNI--DINOv2 Holm-adjusted AUC test: source-weighted for Kather and exploratory tile-weighted for CRC. Kather and conditional CRC subsets require joint correctness; the class-complete CRC analysis explains the true class for all 98 images.",
    "tab:probability_means","lrrrrr","Analysis & $n$ & ResNet18 & DINOv2 & UNI & $p_H$",rows)
for(metric in c(auc,"top_beats_random_probability")) {
    rows<-character()
    for(i in seq_along(scopes)) {
        d<-t[t$scope==scopes[i]&t$metric==metric,]
        stopifnot(nrow(d)==3)
        for(j in seq_len(nrow(d))) {
            contrast<-paste(gsub("ResNet18","R18",d$model_a[j]),"--",gsub("ResNet18","R18",d$model_b[j]))
            rows<-c(rows,paste(c(labels[i],contrast,sprintf("%.4f",d$effect[j]),
                sprintf("[%.4f, %.4f]",d$ci_low[j],d$ci_high[j]),pformat(d$p_holm[j])),collapse=" & "))
        }
    }
    is_auc<-metric==auc
    endpoint<-if(is_auc) "probability-drop AUC" else "probability-based deletion success"
    suffix<-if(is_auc) "auc" else "success"
    table_file(paste0("feedback2_probability_",suffix,"_tests.tex"),
        paste0("Paired contrasts for ",endpoint," under the deterministic tie rule. R18 denotes ResNet18. Effects are first minus second, source-weighted on Kather and tile-weighted on CRC; success effects are proportions. Intervals are pointwise 95\\% bootstrap intervals (5,000 resamples), hierarchical by source then image on Kather and exploratory tile-level on CRC. Each cohort has a six-test Holm family spanning the three model pairs and both probability endpoints."),
        paste0("tab:probability_",suffix,"_tests"),"llrlr",
        "Analysis & Contrast & Effect & 95\\% CI & $p_H$",rows)
}
